[client]
toolbarMode = "minimal"
showSidebarNavigation = true

[theme]
base = "light"
primaryColor = "#DC143C"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7FA"
textColor = "#14171A"
font = "sans serif"

[server]
headless = true
runOnSave = false
port = 8501

[browser]
gatherUsageStats = false
